[package]
name = "wcr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.1.2"
predicates = "3.1.3"
rand = "0.9.2"
