[package]
name = "headr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.54"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
rand = "0.9.2"
